// <auto-generated />
namespace EsadMVCProje.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class denemeBlog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(denemeBlog));
        
        string IMigrationMetadata.Id
        {
            get { return "202301071811233_denemeBlog"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
